# Generated by Django 4.2.3 on 2023-11-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='departure_location',
            field=models.CharField(max_length=50),
        ),
    ]
