# Generated by Django 4.2.3 on 2023-11-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_posts', '0002_alter_ride_departure_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
    ]
